---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  annotations:
    external.dns.koshk.in/provider: "cloudflare"
    external.dns.koshk.in/root-domain: "koshk.in"
spec:
  selector:
    k8s-app: test-app
  ports:
  - port: 80
    targetPort: 80
  type: "LoadBalancer"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: test-app
        ports:
        - containerPort: 80